# Python Programming Assignment â€“ Employee Data Processing

In [1]:
# import libraries
import pandas as pd

In [3]:
# Load CSV
df = pd.read_csv('/content/employee.csv')
df.head()

     EID    Employee Name Gender   Salary Date of Joining Department
0  E123D      Nitin Bhole      M  1900000      01-11-2016   Products
1  E876G   Mayur Kulkarni      M  1200000      03-06-2016  Semantics
2  E798G    Anurag Pandey      M  1200000      04-07-2016         IT
3  E123B    Pankaj Bansal      M   900000      01-12-2015   Research
4  E098Z  Rajendra Prabhu      M  1000000      11-11-2015  Semantics

## 1. Greet Employee by First Name and Gender

In [4]:
def greet_employee(eid):
    emp = df[df['EID'] == eid]
    if emp.empty:
        return "Employee not found."

    name = emp.iloc[0]['Employee Name']
    gender = emp.iloc[0]['Gender']
    first_name = name.split()[0]

    if gender.upper() == 'M':
        return f"Hello, Mr {first_name}"
    elif gender.upper() == 'F':
        return f"Hello, Ms {first_name}"
    else:
        return f"Hello, {first_name}"

# Example
greet_employee("E123D")

'Hello, Mr Nitin'

## 2. Average Salary by Department

In [5]:
def average_salary_by_department():
    avg_salary = df.groupby('Department')['Salary'].mean()
    return avg_salary

average_salary_by_department()

Department
Engineering     650000.0
IT             1200000.0
Products       2075000.0
Research       1350000.0
Semantics      1200000.0
Name: Salary, dtype: float64

## 3. Get Employee Info by EID

In [6]:
def get_employee_info(eid):
    emp = df[df['EID'] == eid]
    if emp.empty:
        return "Employee not found."

    name = emp.iloc[0]['Employee Name']
    doj = emp.iloc[0]['Date of Joining']
    dept = emp.iloc[0]['Department']

    return f"{name} | {doj} | {dept}"

# Example
get_employee_info("E123D")

'Nitin Bhole | 01-11-2016 | Products'

## 4. Sort Employees from Oldest to Newest

In [7]:
def sort_by_joining_date():
    df['Date of Joining'] = pd.to_datetime(df['Date of Joining'], dayfirst=True)
    sorted_df = df.sort_values('Date of Joining')
    return sorted_df[['EID', 'Employee Name', 'Date of Joining', 'Department']]

sort_by_joining_date().head()

      EID      Employee Name Date of Joining   Department
12  E620Y     Kumar Abhishek      2014-12-01    Semantics
7   E184A  Kushmakar Krishna      2015-01-01     Products
4   E098Z    Rajendra Prabhu      2015-11-11    Semantics
8   E104S     Amarnath Patil      2015-11-29  Engineering
3   E123B      Pankaj Bansal      2015-12-01     Research

--------------------------------------------------------------------------------
 # ASSIGNMENT COMPLETED
--------------------------------------------------------------------------------